package com.example.funfacts

import android.R
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.lifecycle.ViewModel

class FactsViewModel : ViewModel() {
    lateinit var name : String
    lateinit var animal : String

    fun generateRandomFact(SelectedAnimal : String): String{
        return if (SelectedAnimal == "Dog") getDogFacts().random() else getCatFacts().random()
    }
    fun getDogFacts() : List<String>{
        val dogFacts = listOf(
            "Dogs belong to the Canidae family.",
            "A dog’s sense of smell is 40 times better than a human’s.",
            "Dogs can hear frequencies between 40 Hz and 60 kHz.",
            "Dogs sweat through their paw pads.",
            "A Greyhound is the fastest dog breed, capable of running 45 mph.",
            "The Basenji is known as the 'barkless dog.'",
            "Dogs have three eyelids, including a third eyelid called a nictitating membrane.",
            "Adult dogs have 42 teeth.",
            "Dogs can understand up to 250 words and gestures.",
            "The Newfoundland breed has webbed feet for swimming.",
            "Dogs have been domesticated for over 14,000 years.",
            "Dogs can detect diseases like cancer in humans.",
            "The tallest dog ever recorded was over 44 inches tall.",
            "Dogs have sweat glands only on their paws.",
            "A dog’s sense of taste is far less developed than humans.",
            "Dogs are omnivores but need meat for protein.",
            "Dogs can see in color, mostly blues and yellows.",
            "Dogs can interpret human emotions by facial expressions.",
            "Dogs can be trained to detect drugs and explosives.",
            "Dogs’ noses are wet to help absorb scent chemicals.",
            "Dogs dream just like humans.",
            "The Labrador Retriever is the most popular dog breed in the USA.",
            "Dogs wag their tails to communicate emotions.",
            "Dogs have been used in police and military roles for centuries.",
            "Dogs can learn by observation and repetition.",
            "Dogs’ sense of hearing is more sensitive than humans.",
            "Dogs can get sunburned, especially light-colored breeds.",
            "Dogs’ whiskers help them sense nearby objects.",
            "Some dog breeds, like the Siberian Husky, have double coats.",
            "Dogs can track humans and animals by scent for miles.",
            "Dogs have an extraordinary memory for commands.",
            "Dogs communicate with barks, growls, and body language.",
            "Dogs can be left or right-pawed.",
            "Dogs’ tails can indicate mood and intent.",
            "Dogs’ vision is better in low light than humans.",
            "Dogs can suffer from separation anxiety.",
            "Dogs can detect changes in the weather or earthquakes.",
            "Dogs’ noses are unique identifiers like human fingerprints.",
            "Some dogs are naturally excellent swimmers.",
            "Dogs use facial expressions to communicate with humans.",
            "Dogs’ hearing range allows them to hear high-pitched sounds.",
            "Dogs can recognize family members and friends.",
            "Dogs’ sense of smell is used in search and rescue operations.",
            "Dogs often show affection by licking humans.",
            "Some dogs are prone to certain genetic health issues.",
            "Dogs can be trained for agility sports.",
            "Dogs can see motion much better than humans.",
            "Dogs have a strong sense of territory.",
            "Dogs use body posture to communicate aggression or submission.",
            "Dogs can interpret human pointing and gestures.",
            "Dogs’ paws are sensitive to heat and cold.",
            "Dogs enjoy playing fetch as a natural instinct.",
            "Dogs’ teeth help in chewing meat and defending themselves.",
            "Dogs can sense human fear and anxiety.",
            "Dogs often bark to alert humans of intruders.",
            "Dogs’ ears can rotate to locate sounds precisely.",
            "Dogs can suffer from obesity if overfed.",
            "Dogs need socialization for mental health.",
            "Dogs can participate in therapy for humans.",
            "Dogs’ coats can indicate health and breed type.",
            "Dogs can form strong bonds with humans.",
            "Dogs’ tail wagging can indicate happiness or nervousness.",
            "Dogs have been companions to humans for thousands of years.",
            "Dogs can recognize emotions through tone of voice.",
            "Dogs’ hearing allows them to detect distant sounds.",
            "Dogs can be trained to assist disabled humans.",
            "Dogs’ eyes have a reflective layer for night vision.",
            "Dogs can differentiate between friendly and hostile humans.",
            "Dogs’ sense of smell is used in detecting contraband.",
            "Dogs can run faster than most humans over short distances.",
            "Dogs’ fur protects them from cold and sun.",
            "Dogs can sense magnetic fields for navigation.",
            "Dogs’ paws contain scent glands.",
            "Dogs can enjoy playing in water or snow.",
            "Dogs can be trained using rewards and commands.",
            "Dogs’ bark pitch varies by breed and size.",
            "Dogs can detect low blood sugar in humans.",
            "Dogs’ whiskers help them detect nearby obstacles.",
            "Dogs may howl to communicate with other dogs.",
            "Dogs’ tails act as balance aids during running.",
            "Dogs have various coat types suited to climate.",
            "Dogs’ digestive systems can tolerate some human food in moderation.",
            "Dogs’ social behavior includes playing, guarding, and hunting.",
            "Dogs can follow scent trails accurately.",
            "Dogs’ noses are moist to trap scent particles.",
            "Dogs can detect some forms of cancer in humans.",
            "Dogs’ teeth and jaws are strong for hunting and chewing.",
            "Dogs can suffer from anxiety when left alone.",
            "Dogs’ behavior can be shaped by training and environment.",
            "Dogs can detect emotional cues from humans.",
            "Dogs’ fur sheds depending on breed and season.",
            "Dogs have been featured in art, literature, and movies for centuries.",
            "Dogs’ life expectancy varies widely by breed.",
            "Dogs’ tail positions can indicate submission, excitement, or alertness.",
            "Dogs can be trained for herding, hunting, or companionship.",
            "Dogs’ paws help with grip and traction.",
            "Dogs’ sense of smell allows them to detect drugs and explosives.",
            "Dogs communicate with humans and other dogs through body language and sound.",
            "Dogs can sense when humans are sad or stressed."
        )
        return dogFacts
    }
    fun getCatFacts() : List<String>{
        val catFacts = listOf(
            "Cats have five toes on their front paws, but only four on the back ones.",
            "A group of cats is called a clowder.",
            "Cats sleep 12-16 hours a day on average.",
            "A cat’s nose is as unique as a human’s fingerprint.",
            "Cats can rotate their ears 180 degrees.",
            "A cat’s whiskers are roughly as wide as its body.",
            "Cats purr for various reasons, including contentment and stress relief.",
            "Domestic cats can run up to 30 mph.",
            "Cats can jump up to six times their body length.",
            "Cats have a third eyelid called a haw.",
            "Cats spend about 70% of their life sleeping.",
            "A cat’s brain is 90% similar to a human’s.",
            "Cats can make over 100 different sounds.",
            "Cats groom themselves using their tongue, which has tiny hooks.",
            "Most cats are lactose intolerant.",
            "Cats can hear ultrasonic sounds up to 64 kHz.",
            "Cats sweat through their paw pads.",
            "The world’s largest cat measured over 48 inches long.",
            "Cats have retractable claws.",
            "Cats use their tail for balance and communication.",
            "Cats can dream just like humans.",
            "Kneading is a comforting behavior from kittenhood.",
            "A cat’s heart beats twice as fast as a human’s.",
            "Some cats have extra toes called polydactyl cats.",
            "Cats can rotate their ears independently.",
            "The oldest recorded cat lived to 38 years.",
            "Cats have better night vision than humans.",
            "Cats can distinguish between different human voices.",
            "Cats can jump from high places safely due to flexible spines.",
            "Cats have scent glands on their cheeks.",
            "Some cats enjoy swimming, but most avoid water.",
            "Cats use whiskers to measure gaps and spaces.",
            "Cats can be left or right-pawed.",
            "A cat’s purring can reduce stress in humans.",
            "Cats can remember faces and locations for years.",
            "Cats groom each other to strengthen social bonds.",
            "A cat’s fur patterns are unique like fingerprints.",
            "Cats can rotate their ears to locate sounds precisely.",
            "White cats with blue eyes are often deaf.",
            "Cats have a strong hunting instinct.",
            "Cats can survive falls from high places due to righting reflex.",
            "Cats communicate using body language, vocalizations, and scent.",
            "Cats can see in near-dark conditions.",
            "Cats’ whiskers are sensitive to air currents.",
            "Cats prefer vertical spaces for security.",
            "A cat’s tongue has backward-facing barbs for grooming.",
            "Cats have 230-250 bones in their body.",
            "Cats’ pupils adjust to light instantly.",
            "Cats can detect earthquakes before humans.",
            "Cats may bring 'gifts' like dead animals to their owners.",
            "Cats’ hearing is superior to dogs’ in high frequencies.",
            "Cats can run short distances faster than humans.",
            "Cats are obligate carnivores.",
            "Cats can suffer from separation anxiety.",
            "Cats mark territory using urine and scent glands.",
            "Cats are crepuscular, active during dawn and dusk.",
            "Cats can distinguish colors but see them differently than humans.",
            "Cats communicate by meowing mostly to humans.",
            "Cats may show affection by slow blinking.",
            "Cats have flexible spines aiding in agility.",
            "Cats’ whiskers detect nearby obstacles.",
            "Cats’ claws retract when relaxed.",
            "Cats can swim but rarely do so voluntarily.",
            "Cats can recognize their own name.",
            "Cats may rub against humans to mark them with scent.",
            "Cats have a strong prey drive, even domesticated ones.",
            "Cats rarely taste sweet flavors.",
            "Cats may knead soft surfaces when happy or relaxed.",
            "Cats’ ears have 32 muscles each.",
            "Cats can overheat due to lack of sweat glands.",
            "Cats groom to reduce stress and regulate temperature.",
            "Cats can detect human emotions and respond accordingly.",
            "Cats often hide pain or illness to avoid predators.",
            "Cats’ retractable claws help in silent hunting.",
            "Cats have strong night vision but poor color vision.",
            "Cats can run in short bursts to catch prey.",
            "Cats may use tail position to communicate mood.",
            "Cats can hear high-frequency sounds humans cannot.",
            "Cats’ whiskers can detect small changes in airflow.",
            "Cats sometimes purr when stressed or in pain.",
            "Cats can adapt to indoor or outdoor lifestyles.",
            "Cats are solitary hunters but can be social.",
            "Cats may hiss or growl when threatened.",
            "Cats can jump vertically over five times their height.",
            "Cats’ paw pads help them detect vibrations.",
            "Cats may have favorite humans.",
            "Cats’ grooming prevents hairballs and parasites.",
            "Cats’ whiskers can help in navigation in the dark.",
            "Cats can learn tricks with patience and reward.",
            "Cats’ claws help them climb and defend themselves.",
            "Cats often knead before sleeping.",
            "Cats may follow a human’s gaze or pointing.",
            "Cats’ tails can indicate happiness or agitation.",
            "Cats’ eyes reflect light due to tapetum lucidum.",
            "Cats can be left or right-pawed.",
            "Cats can develop attachment to other animals.",
            "Cats’ purring can indicate both happiness and distress.",
            "Cats sometimes scratch furniture to sharpen claws.",
            "Cats’ tongues are rough due to papillae.",
            "Cats can be trained using positive reinforcement.",
            "Cats’ heart rate ranges between 140-220 bpm.",
            "Cats’ sense of smell is much stronger than humans'.",
            "Cats may play with toys to practice hunting skills.",
            "Cats can be allergic to humans too.",
            "Cats can recognize their owner’s voice.",
            "Cats’ fur helps regulate body temperature.",
            "Cats have excellent balance due to inner ear structure."
        )
        return catFacts
    }
}